[workspace]

members = [
    "cli",
    "client",
    "common",
    "config",
    "consensus",
    "execution",
]

[patch.crates-io]
ethers = { git = "https://github.com/ncitron/ethers-rs", branch = "fix-retry" }
