[package]
name = "helios"
version = "0.1.1"
edition = "2021"

[workspace]

members = [
    "cli",
    "client",
    "common",
    "config",
    "consensus",
    "execution",
]

[dependencies]
client = { path = "./client" }
config = { path = "./config" }
common = { path = "./common" }
consensus = { path = "./consensus" }
execution = { path = "./execution" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6.8"
home = "0.5.4"
ethers = "1.0.2"
env_logger = "0.9.0"
log = "0.4.17"

[[example]]
name = "checkpoints"
path = "examples/checkpoints.rs"

[[example]]
name = "readme"
path = "examples/readme.rs"

[[example]]
name = "client"
path = "examples/client.rs"

[[example]]
name = "config"
path = "examples/config.rs"

